export const storageStockColumnsForItemWise = [
    { Column_Name: 'Trans_Date', Data_Type: 'date' },
    { Column_Name: 'Group_Name', Data_Type: 'string' },
    { Column_Name: 'stock_item_name', Data_Type: 'string' },
    { Column_Name: 'OB_Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'OB_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Qty', Data_Type: 'number' },
    { Column_Name: 'Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'Bal_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Stock_Item', Data_Type: 'string' },
    { Column_Name: 'Group_ST', Data_Type: 'string' },
    { Column_Name: 'Bag', Data_Type: 'string' },
    { Column_Name: 'Stock_Group', Data_Type: 'string' },
    { Column_Name: 'Product_Rate', Data_Type: 'number' },
    { Column_Name: 'S_Sub_Group_1', Data_Type: 'string' },
    { Column_Name: 'Grade_Item_Group', Data_Type: 'string' },
    { Column_Name: 'Item_Name_Modified', Data_Type: 'string' },
];

export const storageStockColumnsForGodownWise = [
    // { Column_Name: 'Trans_Date', Data_Type: 'date' },
    { Column_Name: 'Godown_Name', Data_Type: 'string' },
    { Column_Name: 'stock_item_name', Data_Type: 'string' },
    { Column_Name: 'OB_Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'OB_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Qty', Data_Type: 'number' },
    { Column_Name: 'Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'Act_Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Stock_Item', Data_Type: 'string' },
    { Column_Name: 'Group_ST', Data_Type: 'string' },
    { Column_Name: 'Bag', Data_Type: 'string' },
    { Column_Name: 'Stock_Group', Data_Type: 'string' },
    { Column_Name: 'Product_Rate', Data_Type: 'number' },
    { Column_Name: 'S_Sub_Group_1', Data_Type: 'string' },
    { Column_Name: 'Grade_Item_Group', Data_Type: 'string' },
    { Column_Name: 'Item_Name_Modified', Data_Type: 'string' },
]

export const itemGroupWiseStockValue = [
    { Column_Name: 'Group_Name', Data_Type: 'string' },
    { Column_Name: 'Brand', Data_Type: 'string' },
    { Column_Name: 'Group_ST', Data_Type: 'string' },
    { Column_Name: 'Stock_Group', Data_Type: 'string' },
    { Column_Name: 'S_Sub_Group_1', Data_Type: 'string' },
    { Column_Name: 'Grade_Item_Group', Data_Type: 'string' },
    { Column_Name: 'Trans_Date', Data_Type: 'date' },
    
    { Column_Name: 'OB_Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'OB_Rate', Data_Type: 'number' },
    { Column_Name: 'OB_Value', Data_Type: 'number' },
    { Column_Name: 'Pur_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Rate', Data_Type: 'number' },
    { Column_Name: 'Pur_value', Data_Type: 'number' },
    { Column_Name: 'Adj_Pur_Qty', Data_Type: 'number' },
    { Column_Name: 'Adj_Pur_Rate', Data_Type: 'number' },
    { Column_Name: 'Adj_Pur_value', Data_Type: 'number' },
    { Column_Name: 'IN_Qty', Data_Type: 'number' },
    { Column_Name: 'IN_Rate', Data_Type: 'number' },
    { Column_Name: 'IN_Value', Data_Type: 'number' },
    { Column_Name: 'Sal_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Rate', Data_Type: 'number' },
    { Column_Name: 'Sal_value', Data_Type: 'number' },
    { Column_Name: 'Adj_Sal_Qty', Data_Type: 'number' },
    { Column_Name: 'Adj_Sal_Rate', Data_Type: 'number' },
    { Column_Name: 'Adj_Sal_value', Data_Type: 'number' },
    { Column_Name: 'OUT_Qty', Data_Type: 'number' },
    { Column_Name: 'Out_Rate', Data_Type: 'number' },
    { Column_Name: 'Out_Value', Data_Type: 'number' },
    { Column_Name: 'Expense_value', Data_Type: 'number' },
    { Column_Name: 'Act_Expense', Data_Type: 'number' },
    { Column_Name: 'Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'CL_Rate', Data_Type: 'number' },
    { Column_Name: 'CL_Value', Data_Type: 'number' },
    { Column_Name: 'CR_CL_Rate', Data_Type: 'number' },
    { Column_Name: 'Pre_Qty', Data_Type: 'number' },
    { Column_Name: 'Pre_Rate', Data_Type: 'number' },
    { Column_Name: 'Pre_CL_Value', Data_Type: 'number' },
]