export const storageStockColumns = [
    { Column_Name: 'Trans_Date', Data_Type: 'date' },
    { Column_Name: 'Group_Name', Data_Type: 'string' },
    { Column_Name: 'stock_item_name', Data_Type: 'string' },
    { Column_Name: 'OB_Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'OB_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Qty', Data_Type: 'number' },
    { Column_Name: 'Bal_Qty', Data_Type: 'number' },
    { Column_Name: 'Bal_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Pur_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Sal_Act_Qty', Data_Type: 'number' },
    { Column_Name: 'Stock_Item', Data_Type: 'string' },
    { Column_Name: 'Group_ST', Data_Type: 'string' },
    { Column_Name: 'Bag', Data_Type: 'string' },
    { Column_Name: 'Stock_Group', Data_Type: 'string' },
    { Column_Name: 'Product_Rate', Data_Type: 'number' },
    { Column_Name: 'S_Sub_Group_1', Data_Type: 'string' },
    { Column_Name: 'Grade_Item_Group', Data_Type: 'string' },
    { Column_Name: 'Item_Name_Modified', Data_Type: 'string' },
]