import { ISOString } from "../../../Components/functions";
import { getSessionUser } from "../../../Components/functions";

const { user } = getSessionUser();

export const tripMasterDetails = {
    Trip_Id: '',
    Challan_No: '',
    Branch_Id: '',
    Trip_Date: ISOString(),
    Vehicle_No: '',
    StartTime: '',
    EndTime: '',
    Trip_No: '',
    Trip_ST_KM: '',
    Trip_EN_KM: '',
    Trip_Tot_Kms: '',
    Godownlocation: '',
    LoadingLoad: '',
    LoadingEmpty: '',
    UnloadingLoad: '',
    UnloadingEmpty: '',
    MachineNo: '',
    PhoneNumber: '',
    BillType: '',
    VoucherType: '',
    Narration: '',
    Created_By: user.UserId,
    Updated_By: user.UserId,
}

export const tripDetailsColumns = {
    Id: '',
    Trip_Id: '',
    STJ_Id: '',
    Batch_No: '',
    Journal_no: '',
    From_Location: '',
    To_Location: '',
    S_No: '',
    Concern: '',
    BillNo: '',
    BatchLocation: '',
    Product_Id: '',
    HSN_Code: '',
    QTY: 0,
    KGS: 0,
    Units: '',
    Unit_Id: '',
    GST_Inclusive: 1,
    IS_IGST: 0,
    Gst_Rate: 0,
    Gst_P: 0,
    Cgst_P: 0,
    Sgst_P: 0,
    Igst_P: 0,
    Taxable_Value: 0,
    Round_off: 0,
    Total_Value: 0,
    Trip_From: 'STOCK JOURNAL',
    Party_And_Branch_Id: 1,
    Transporter_Id: 0,
    Created_By: user.UserId,
    Updated_By: user.UserId,
}

export const tripStaffsColumns = {
    Id: '',
    Trip_Id: '',
    Involved_Emp_Id: '',
    Cost_Center_Type_Id: '',
    Emp_Name: '',
}